export const ActionTypes = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_ALL_TODOS: 'REMOVE_ALL_TODOS',
    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    FETCH_QUOTES_BEGIN: 'FETCH_QUOTES_BEGIN',
    FETCH_QUOTES_SUCCESS: 'FETCH_QUOTES_SUCCESS',
    FETCH_QUOTES_FAILURE: 'FETCH_QUOTES_FAILURE',
    FETCH_BACKGROUND_BEGIN: 'FETCH_BACKGROUND_BEGIN',
    FETCH_BACKGROUND_SUCCESS: 'FETCH_BACKGROUND_SUCCESS',
    FETCH_BACKGROUND_FAILURE: 'FETCH_BACKGROUND_FAILURE'

}